// Permission.java
package com.example.Advances.Banking.System.core.enums;

public enum Permission {
    VIEW_OWN_ACCOUNTS,
    MAKE_TRANSFERS,
    VIEW_TRANSACTIONS,
    CREATE_SUPPORT_TICKET,
    VIEW_STATEMENTS,
    VIEW_CUSTOMER_ACCOUNTS,
    PROCESS_DEPOSITS,
    PROCESS_WITHDRAWALS,
    VIEW_ALL_TRANSACTIONS,
    CREATE_ACCOUNTS,
    UPDATE_CUSTOMER_INFO,
    APPROVE_LARGE_TRANSACTIONS,
    MANAGE_TELLERS,
    VIEW_BRANCH_REPORTS,
    FREEZE_ACCOUNTS,
    VIEW_AUDIT_LOGS,
    GENERATE_REPORTS,
    MANAGE_SYSTEM_CONFIG,
    MANAGE_ALL_ACCOUNTS,
    VIEW_SYSTEM_LOGS,
    USER_MANAGEMENT,
    DATABASE_ACCESS,
    BACKUP_RESTORE;
}